require 'net/http'
require 'base64'
require 'ostruct'
require 'logger'
require 'json'
require 'uri'
require 'pg'

require './config/followers'
require './lib/followers/twitter_client'
require './lib/followers/comparison'
require './lib/mailer'
require './lib/followers/updater'
