require 'net/http'
require 'ostruct'
require 'oauth'
require 'json'
require 'uri'

require './config/followers'
require './lib/oauth_client'
require './lib/followers/twitter_client'
require './lib/followers/comparison'
